### ISSUE TITLE
Check .npmignore

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.repochecker#24]
Warning if **.npmignore** not found.
Error if folder/file exits, but not ignored:
- test
- node_modules
- .git
- .idea
- .github
- src
- .gitignore
- .npmignore
- .travis.yml
- appveyor.yml

**Comment by AlCalzone** [comment]
I think this check should be extended, because it can generate a lot of false positives.

An alternative to blacklisting files is whitelisting them in `package.json` -> `files`: https://github.com/AlCalzone/ioBroker.zwave2/blob/71e1c813bf8c939e4a334f29db04f47a250ec58f/package.json#L23-L30

Therefore the check for forbidden files should be:
Is the file in .npmignore? If yes, ok
If not, is the file included in `files`? If not, ok.
Else issue the warning.

**Comment by AlCalzone** [comment]
Maybe it would be easier to leverage `npm` for this check. By doing a `dry-run` pack, you can figure out which files end up in the package. Here's an example how we do it in `create-adapter`:
```
const packageContent = JSON.parse(
	execa.sync("npm", ["pack", "--dry-run", "--json"], {
		cwd: testDir,
		encoding: "utf8",
	}).stdout,
);
const packageFiles = packageContent[0].files.map(f => f.path);
// Test these ^
```

**Comment by klein0r** [comment]
@AlCalzone Good solution! I'm getting `[W801] .npmignore not found` right now, because I'm using the `files` array in `package.json` instead of `.npmignore`

**Comment by GermanBluefox** [comment]
package.json files will be checked
